Iter13
ANiWarlock/yandex_go_url_sh pull request #13
Opened 2023-06-13 09:04 UTC by ANiWarlock

2023-06-17 17:04 UTC, s-shpak requested changes

2023-06-17 17:04 UTC, s-shpak commented on internal/app/handlers.go
> +	if err = a.storage.SaveLongURL(hashedURL, longURL); err != nil {
Я бы объединил этот хендлер с `GetShortURLHandler`, чтобы избежать дупликации логики

2023-06-17 17:04 UTC, s-shpak commented on internal/app/handlers.go
> +	for _, v := range apiReq {
Сейчас это не батчинг, это запись данных в БД по очереди. В идеале, ты должен делать фиксированное количество запросов к БД (один, например), которое не должно зависеть от количества отправляемых данных. Для батчинга можно:
1. перейти на `pgx` вместо `db/sql`
2. формировать запрос самому
3. использовать библиотеку типа `sqlx` или `squirrel`

2023-06-17 17:04 UTC, s-shpak commented on storage/storage.go
> +	db       *sql.DB
Мне очень не нравится, что в текущей реализации в этом объекте лежит все три имплементации БД. Если я использую постгрес, то моя структура не должна знать ничего о работе с файловой системой, например. Думаю, пришло время раделить этот тип на три разных

2023-06-17 17:04 UTC, s-shpak commented on storage/storage.go
> +		if err := s.saveItemToDB(item); err != nil {
Если ты делаешь два (или несколько) запроса к БД, то их необходимо оборачивать в транзакцию. Но в случае постгреса множественные запросы не требуются, т.к. есть конструкция `INSERT...ON CONFLICT`

2023-06-17 17:04 UTC, s-shpak commented on storage/storage.go
> +func (s *Storage) PingDB() bool {
Я бы просто возвращал ошибку вместо `bool`

2023-06-17 17:04 UTC, s-shpak commented on storage/storage.go
> +	if s.db != nil {
Чтобы сделать код более плоским я бы сначала проверил `s.db == nil`

2023-06-21 22:24 UTC, ANiWarlock commented on internal/app/handlers.go
> +	if err = a.storage.SaveLongURL(hashedURL, longURL); err != nil {
Довольно странный получился хендлер, но все в одном месте:)

2023-06-22 18:16 UTC, s-shpak commented on internal/app/handlers.go
> +	if err = a.storage.SaveLongURL(hashedURL, longURL); err != nil {
В принципе нормально, но можно было вынести в одну функцию центарльную логику, и использовать два хендлера для обработки запроса и ответа

2023-06-22 18:25 UTC, s-shpak requested changes

2023-06-22 18:25 UTC, s-shpak commented on storage/db.go
> +	_, err = conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS urls (id SERIAL PRIMARY KEY , short varchar(16) NOT NULL, long varchar(255) NOT NULL)")
Создание таблицы тоже должно быть обернуто в транзакцию, т.к. ты отправляешь два запроса. Но можно обойтись одним: просто добавить аттрибут `UNIQUE` в определение колонки

2023-06-22 18:25 UTC, s-shpak commented on storage/db.go
> +	conn *pgx.Conn
Лучше использовать `pgxpool`: `pgx.Conn` неконкурентно безопасный объект

2023-06-22 18:25 UTC, s-shpak commented on storage/db.go
> +type UniqueViolationError struct {
Необязательно создавать отдельный тип для ошибки: можно объявить глобальную переменную-ошибку, и использовать ее так:

```go
var ErrUniqueViolation = errors.New("unique violation error")
...
func doSmth(shortURL string) error {
...
    return fmt.Errorf("%w: %s", ErrUniqueViolation, shortURL)
}
```

2023-06-22 18:25 UTC, s-shpak commented on storage/db.go
> +	conn, err := pgx.Connect(context.Background(), cfg.DatabaseDSN)
Контекст лучше передавать извне первым аргументом (можно оставить это до следующего спринта)

2023-06-22 18:25 UTC, s-shpak commented on cmd/shortener/main.go
> +		defer store.CloseDB()
`CloseDB` должно вызваться, даже если пинг не прошел, т.к. объект был успешно проинициализирован выше

2023-06-23 12:41 UTC, ANiWarlock commented on storage/db.go
> +	conn, err := pgx.Connect(context.Background(), cfg.DatabaseDSN)
Оставим до след спринта

2023-06-23 13:54 UTC, ANiWarlock commented on storage/db.go
> +type UniqueViolationError struct {
Тогда не получается использовать errors.As (go vet test жалуется)

2023-06-23 16:24 UTC, s-shpak commented on storage/db.go
> +type UniqueViolationError struct {
А зачем тебе использовать `errors.As` в этом случае? Используй `errors.Is`

2023-06-23 16:25 UTC, s-shpak requested changes
См. последний комментарий

2023-06-23 16:33 UTC, ANiWarlock commented on storage/db.go
> +type UniqueViolationError struct {
Логично

2023-06-23 16:53 UTC, s-shpak approved these changes

2023-06-23 17:01 UTC, merged