Iter15
ANiWarlock/yandex_go_url_sh pull request #15
Opened 2023-06-27 12:30 UTC by ANiWarlock

2023-06-29 17:47 UTC, s-shpak requested changes

2023-06-29 17:47 UTC, s-shpak commented on internal/app/handlers.go
> +	tokenString, _ := r.Cookie("auth")
1. Ошибки надо проверять даже если пердпоалагается, что ты уже проверил валидность в middleware
2. Лучше передать проверенный ID через контекст запроса. Здесь описано как лучше выставить ключ внутри контекста: https://bongnv.com/blog/2021-04-10-safely-use-go-context-to-pass-data/

2023-06-29 17:47 UTC, s-shpak commented on internal/app/handlers.go
> +		a.sugar.Errorf("no user items: %v", err)
Это не ошибка, нет смысла ее логировать

2023-06-29 17:47 UTC, s-shpak commented on internal/app/handlers.go
> +		a.storage.BatchDeleteURL(context.Background(), items)
Запросов к БД (и следовательно соединений) может быть очень много, лучше ограничить количество одновременных соединений. Лучше сделать это через конфигурацию Pool'а

2023-06-29 17:47 UTC, s-shpak commented on lib/auth/auth.go
> +const secret = "secretKey"
Я понимаю, что в задании этого нет, но давай сделаем возможным определять ключ при старте сервера

2023-06-29 17:47 UTC, s-shpak commented on lib/auth/auth.go
> +	tokenString, _ := token.SignedString([]byte(secret))
Ошибки надо проверять

2023-06-29 17:47 UTC, s-shpak commented on router/middleware/auth.go
> +			setCookie(rw, r)
Если токен есть, но невалиден, то лучше это залогировать

2023-06-29 17:47 UTC, s-shpak commented on storage/file.go
> +	return nil, nil
Лучше реализовать это и для файлового хранилища. Это не будет очень трудным - достаточно заимплементить это для хранилища в памяти

2023-06-29 17:47 UTC, s-shpak commented on storage/mem.go
> +	//реализовано для DB
Необходимо реализовать

2023-07-03 16:25 UTC, ANiWarlock commented on internal/app/handlers.go
> +		a.storage.BatchDeleteURL(context.Background(), items)
добавил настройку в db.go

2023-07-04 05:46 UTC, s-shpak requested changes

2023-07-04 05:46 UTC, s-shpak commented on lib/auth/auth.go
> +const CtxKeyUserID ctxKey = "ctxUserID"
Используй лучше `iota`

2023-07-04 05:46 UTC, s-shpak commented on router/middleware/auth.go
> +		if err != nil {
Для того чтобы отправить `Unauthorized` пользователю стоит проверить на конкретную ошибку

2023-07-04 05:46 UTC, s-shpak commented on storage/db.go
> +const MaxConns = 20
Нет смысла экспортировать

2023-07-04 05:46 UTC, s-shpak commented on storage/mem.go
> +	//реализовано для DB
Для memstore должен быть реализован весь интерфейс store

2023-07-04 05:46 UTC, s-shpak commented on storage/file.go
> +	//реализовано для DB
См. коммент для memorystore

2023-07-07 14:08 UTC, s-shpak approved these changes

2023-07-07 14:09 UTC, merged