Iter9
ANiWarlock/yandex_go_url_sh pull request #9
Opened 2023-05-30 17:38 UTC by ANiWarlock

2023-05-31 19:44 UTC, s-shpak requested changes

2023-05-31 19:44 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatalf("Cannot init logger: %s", err)
Ошбики лучше оборачивать через `%v` (в случае логгирования)

2023-05-31 19:44 UTC, s-shpak commented on logger/logger.go
> +var Sugar *zap.SugaredLogger
Глобальные переменные не нужны: возвращай логгер из функции инициализации и передавай его там, где нужно

2023-05-31 19:44 UTC, s-shpak commented on logger/logger.go
> +		return err
Сторонние ошибки надо оборачивать + лучше залогировать проблемное значение уровня

2023-05-31 19:44 UTC, s-shpak commented on storage/storage.go
> +	if cfg.Filename != "" {
`else` не нужен

2023-05-31 19:44 UTC, s-shpak commented on storage/storage.go
> +	if s.filename != "" {
Можно проверить обратное, выйти заранее и, таким образом, сделать код более плоским

2023-05-31 19:44 UTC, s-shpak commented on router/middleware/compress.go
> +	w  http.ResponseWriter
Это поле можно "встроить", тогда функцию `Write` не придется переопределять

2023-05-31 19:44 UTC, s-shpak commented on internal/app/handlers_test.go
> +	store, _ := storage.InitStorage(*cfg)
Ошибки надо проверять и в тестах

2023-05-31 19:44 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, err.Error(), http.StatusInternalServerError)
Для `Internal Server Error` текст ошибки не стоит возвращать пользователю, но стоит залогировать

2023-06-05 14:09 UTC, ANiWarlock commented on router/middleware/compress.go
> +	w  http.ResponseWriter
Не понял как это правильно сделать

2023-06-05 14:09 UTC, ANiWarlock commented on logger/logger.go
> +		return err
Оборачивать во что?

2023-06-05 14:55 UTC, s-shpak requested changes

2023-06-05 14:55 UTC, s-shpak commented on logger/logger.go
> +		log.Printf("Bad zap.logger level: %s", level)
нет никакого смысла логгировать ошибку здесь: пробрасывай ее максимально наверх и логгируй там (пока функция возвращает ошибку не стоит ее логгировать внутри нее)

2023-06-05 14:55 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, fmt.Sprintf("Error in request body: %v", err), http.StatusBadRequest)
Это внутренняя ошибка: в нормальной ситуации ты должен иметь возможность прочитать боди. Если `buf.ReadFrom` возвращает ошибку, то произошло что-то неординарное. В данном случае нельзя отдавать пользователю информацию об ошибке из соображений безопасности. Ограничься стандартным сообщением (это касается и других ошибок в этой функции)

2023-06-07 11:53 UTC, ANiWarlock commented on storage/storage.go
> +	if s.filename != "" {
Раньше уже вроде некуда)

2023-06-07 11:56 UTC, ANiWarlock commented on router/middleware/compress.go
> +	w  http.ResponseWriter
Но мне же нужно использовать gzip Writer?  таким образом разве то лишний Header() можно убрать, если я все правильно понял

2023-06-07 14:33 UTC, s-shpak commented on logger/logger.go
> +		return err
`return fmt.Errorf("failed to parse the logging level %s: %w", level, err)`

2023-06-07 14:35 UTC, s-shpak commented on storage/storage.go
> +	if s.filename != "" {
Прошу прощения, прокомментировал не ту строку

2023-06-07 14:35 UTC, s-shpak commented on router/middleware/compress.go
> +	w  http.ResponseWriter
Все верно

2023-06-07 15:11 UTC, s-shpak requested changes

2023-06-07 15:11 UTC, s-shpak commented on cmd/shortener/main.go
> +	sugar.Fatal(http.ListenAndServe(cfg.Host, shortRouter))
`sugr.Fatal` будет всегда приводить к аварийному завершению. Лучше проверить вернулась ли ошибка и вызвать `sugar.Fatal` только если вернулась

2023-06-07 15:11 UTC, s-shpak commented on cmd/shortener/main_test.go
> +	store, _ := storage.InitStorage(*cfg)
Ошибки надо проверять и в тестах

2023-06-07 15:11 UTC, s-shpak commented on storage/storage.go
> +	if cfg.Filename != "" {
Я имел в виду провертиь уловие `if cfg.Filename == ""` здесь

2023-06-07 15:11 UTC, s-shpak commented on storage/storage.go
> +			return err
Обертка ошибок:

```suggestion
			return fmt.Errorf("failed to unmarshal a line from the file storage document: %w", err)
```

2023-06-07 16:26 UTC, s-shpak approved these changes

2023-06-07 18:03 UTC, merged